### PR TITLE
fix for project sort order

### PR DESCRIPTION
**Pull request by JW-Vinayak**
This is in reference with [this issue](https://github.com/monaca/monaca_localkit/issues/30)

### CODE REVIEW

**Comment by argelius** [comment]
@JW-Vinayak Does this fix it? I can merge it if you're sure that this fixes the bug, but actually there is a problem.

JavaScript doesn't guarantee key order. The projects are added with

``` javascript
this.projects[id] = project
```

and V8 seems to put them at the end, but this behavior is not defined in the ECMAScript spec, so another engine could do something else or the V8 behavior could be changed at any time.

**Comment by JW-Vinayak** [comment]
@argelius This code surely fixes the bug. I have checked this code on Windows and Mac and works fine ! 

Since I am emptying the project list before adding new project, all the existing projects are then appended at the end, this maintains the order.

**Comment by argelius** [comment]
@JW-Vinayak 

Sure, but there's no way to know that since it's undefined behavior:
http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order#answer-5525820

Can't we just use an Array and unshift in order to put the object at the start? This approach seems overly complicated.

**Comment by JW-Vinayak** [comment]
Sure @argelius , I will do it.

**Comment by argelius** [comment]
Thanks @JW-Vinayak !

**Comment by JW-Vinayak** [comment]
Hi @argelius 

Please review this implementation and do let me know if any other change is needed.

**Comment by argelius** [comment]
Thanks @JW-Vinayak ! Looks like the order will be correct now.

**Pull request merged**
