### PR TITLE
Remove stylus loader

### PR DESCRIPTION
**Pull request by adamkozuch**

### CODE REVIEW

**Comment by masahirotanaka** [comment]
I saw the change. If we remove this, the existing projects will fail to compile?

**Comment by asial-matagawa** [comment]
@masahirotanaka 
Since `additionalDependencies` of `monaca-lib` still has `stylus-loader`, they will not fail to compile.
https://github.com/monaca/monaca-lib/blob/4fec74af026635042175814f2c45a9a4ebf1dc6a/package.json#L73

**Comment by masahirotanaka** [comment]
@asial-matagawa Thanks for the explanation. If CLI still is able to compile the existing templates, there is no reason to remove this from the Webpack config.

**Comment by frandiox** [comment]
> there is no reason to remove this from the Webpack config.

@masahirotanaka This rule will only be applied to new projects where users have Stylus in their custom code, not in Onsen UI. I think we can safely remove it since, if they want to use Stylus, they can add it themselves. We also removed SASS because it has nothing to do with Onsen UI.

Old libs will create projects with the previous configuration, so they will work fine with old Onsen UI versions. Also, if for some reason they update CLI and reinstall all the dev-dependencies but keep some old projects, Stylus will keep working since we still have `stylus-loader` dependency (it will be installed again even though new projects don't use it).

The current configuration in this branch is broken due to an error thrown by Stylus + cssnext. We either remove Stylus or create another configuration for Stylus with an extra autoprefixer dependency.

**Pull request merged**
