### PR TITLE
Emitter support

### PR DESCRIPTION
**Pull request by andipavllo**
@masahirotanaka please take a look at this. It adds emitter support for monaca-lib, allowing to improve the communication between lib and cli/localkit.

### CODE REVIEW

**Comment by masahirotanaka** [comment]
Thank you. I looked the code but I cannot accept the change at the moment. I'll talk about it later.

**Comment by erisu** [comment]
# Alternative Specs

Example emitter **event name** `output` with **event data**

```
{
    "type": "error|warn|info|success",
    "message": ""
}
```

Example emitter **event name** `process` with **event data**

```
{
    "id": "downloadTemplate",
    "state": "start|stop|...",
    "message": ""
}
```

**Comment by masahirotanaka** [comment]
Thanks. In my point of view, returning `projectDir` does not mean anything, since that is the parameter passed to the function. Do you have any other idea what this function can return as the result?

**Comment by andipavllo** [comment]
I don't think there is anything more relevant to return. Or `projectDir` or nothing.

**Comment by masahirotanaka** [comment]
How about returning more details the transpile result, i.e. files changed, warnings & notices etc...

**Comment by andipavllo** [comment]
Of course, I considered them but WebPack just returns:

```
errors
warnings
version
hash
time
publicPath
assetsByChunkName
assets
chunks
modules
filteredModules
children
```

The only one that would make sense is `warnings`, but there is already a handler for them, which is not being used at the moment. I don't know what plans Bryan has for it.

Moreover, what about `_npmInstall` and `installTemplateDependencies` functions (just to take some examples, they have nothing to do with pull request)? They both take `projectDir` as input argument and still return `projectDir` while solving the promise. Why were those implementations not rejected at the time?

Nevertheless, this is just 1 of the 3 cases in which the promise will be resolved. What do you want to return in the other two? The returning values would not be consistent between the 3 cases.

**Comment by masahirotanaka** [comment]
Yes, I suggest those functions to return everything that can be assumed to use later on. It's a better design philosophy, and I'm not talking about the actual needs.

`_npmInstall` is not a public function, so we don't need to expose unused return values. `installTemplateDependencies` can return useful information if they exist.

Also, the return type should be consistent in all Promise returns. Otherwise caller should be very careful.

**Comment by andipavllo** [comment]
@masahirotanaka I guess this implementation will fit the specs.
- On resolve, all the promises return an object. Stats are included if the transpiling has been executed and the possible warnings are included in the emit content.
- On reject, all the promises return an Error.

**Comment by masahirotanaka** [comment]
Well done @andipavllo. Looks very good :+1:

**Pull request merged**
