### PR TITLE
implemented getConfigSync method

### PR DESCRIPTION
**Pull request by JW-Vinayak**
This pull request is in reference with [this](https://github.com/monaca/monaca_localkit/issues/44) and [this](https://github.com/monaca/monaca_localkit/issues/42) enhancements.

### CODE REVIEW

**Comment by argelius** [comment]
Hi!

Please don't use `require` to read the file since it will only work once because `require` caches files. Use sync file io and `JSON.parse`.

**Comment by argelius** [comment]
Also, I think it's better if it just returns the config value. Please throw an error if something goes wrong so we can catch it.

**Comment by JW-Vinayak** [comment]
Hi Andreas,

Thank you for suggestions! I have modified the code accordingly.

**Comment by argelius** [comment]
Thanks @JW-Vinayak ! Looks good.

**Pull request merged**
