### PR TITLE
Read/Write config files refactor.

### PR DESCRIPTION
**Pull request by frandiox**
@masahirotanaka This avoids opening, reading and closing the same file several times for the same action. It keeps a copy of `monaca.json` in memory and updates the file when needed.
This also removes some code duplications like `Monaca.prototype.removeConfig`.

### CODE REVIEW

**Comment by masahirotanaka** [comment]
Saw the code. It looks good. 
Please be sure `setConfig()` is called after`setData()`. Maybe better to rename it to `saveConfig()` for clarification?

**Comment by frandiox** [comment]
@masahirotanaka There are 2 different and independent files. One is `monaca.json` where we write and read with `getData` and `setData`, and another one is `monaca_config.json` (where basically the proxy info is saved), where we write and read with `setConfig` and `getConfig`. If I didn't miss anything I think there is no need to call `setConfig` after `setData`. `setData` already calls `_saveAllData` to persist changes. I don't like the names too much but I didn't want to change them just to keep the PR more understandable.

Also, I think `setConfigFile` is not used in any other part.

**Comment by masahirotanaka** [comment]
Thanks for the clarification @frankdiox.
@argelius Do you remember why we separated `monaca.json` and `monaca_config.json`? Maybe I demanded for it, but honestly I forgot why.

**Comment by masahirotanaka** [comment]
Anyways, let's then keep the function names as they are for now. Merging the pull-request.

**Pull request merged**
